### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by rlinocit** [and3rson/nineapi#1]
I got your library working in my project, but 9gag limits the count of posts in each request.

Would it be possible to paginate the requests?

Thanks!

**Comment by and3rson** [comment]
Hi!

Sorry for the delay. I've finally got some time and I'll check out what can be done here.

**Comment by Marekkon5** [comment]
Also want to see this... To scrap like 1000 posts ;)

**Comment by and3rson** [comment]
@rlinocit @Marekkon5 I just went through the network dump and figured out that they use `olderThan` parameter for this. I've pushed the updated `get_posts` method that handles this parameter.

For example, to fetch first 5 pages, 10 posts each::

```python
last_post = None
for _ in range(5):
    posts = c.get_posts(olderThan=last_post)  # Pass `None` or ignore param to fetch first page.
    for post in posts:
        print(post.id, post.title)
    last_post = posts[-1]
```

Glad if it helps. Feel free to reopen this issue if there are any problems. :)

**Comment by and3rson** [comment]
Also don't forget you can pass larger `count` kwarg to `get_posts` method.
