### ISSUE TITLE
Emoji Unicode

### ISSUE THREAD

**Issue by Marekkon5** [and3rson/nineapi#2]
Since there are emojis in posts names on 9gag......... my app crashed due to unicode not-supported.

U0001f4cc - is pin emoji from https://9gag.com/gag/a05LDmv

Traceback (most recent call last):
  File "mytest.py", line 11, in <module>
    print(post)
  File "/home/pi/nineapi/nineapi/client.py", line 193, in __str__
    self.url
UnicodeEncodeError: 'ascii' codec can't encode character u'\U0001f4cc' in position 0: ordinal not in range(128)

**Comment by Marekkon5** [comment]
https://github.com/Marekkon5/nineapi/commit/9771b1db1d2c1c20602abe328529deb948688efd

My fix

**Comment by and3rson** [comment]
Hi, thanks for the fix! I've merged it from your fork.
